package org.sunbird.learning.common.enums;

public enum ContentErrorCodes {
	 ERR_CONTENT_BLANK_OBJECT, ERR_CONTENT_INVALID_UPLOAD_OBJECT,
	    ERR_CONTENT_BLANK_OBJECT_ID, ERR_CONTENT_INVALID_OBJECT_TYPE, ERR_CONTENT_INVALID_PARAM, 
	    ERR_CONTENT_BLANK_UPLOAD_OBJECT, ERR_CONTENT_UPLOAD_NO_SUPPORT, ERR_CONTENT_UPLOAD_FILE, 
	    ERR_CONTENT_INVALID_SEARCH_CRITERIA, ERR_CONTENT_INVALID_BUNDLE_CRITERIA, ERR_CONTENT_NOT_FOUND, 
	    ERR_CONTENT_BLANK_ID, ERR_CONTENT_BLANK_UPLOAD_RESOURCE, ERR_CONTENT_BLANK_PUBLISHER, 
	    ERR_CONTENT_PUBLISH, ERR_CONTENT_MANIFEST_PARSE_ERROR, ERR_CONTENT_INVALID_PLUGIN_ID, 
	    ERR_CONTENT_MISSING_VERSION, ERR_CONTENT_EXTRACT, ERR_INVALID_RELATION_NAME, 
	    ERR_ECAR_BUNDLE_FAILED, ERR_CONTENT_SEARCH_ERROR ,ERR_CONTENT_JSON_INVALID,
	    ERR_CONTENT_BODY_INVALID, ERR_CONTENT_WP_JSON_PARSE_ERROR, ERR_CONTENT_WP_XML_PARSE_CONFIG_ERROR, 
	    ERR_CONTENT_WP_NOT_WELL_FORMED_XML, ERR_CONTENT_WP_XML_IO_ERROR, ERR_CONTENT_WP_OBJECT_CONVERSION, 
	    ERR_CONTENT_OPTIMIZE, INVALID_NODE, INVALID_EXTRACTION, INVALID_ECAR, INVALID_ARTIFACT, INVALID_FILE, 
	    EXTRACTION_ERROR, UPLOAD_DENIED, INVALID_SNAPSHOT, OPERATION_DENIED, INVALID_YOUTUBE_URL, 
	    MISSING_YOUTUBE_URL, MISSING_FILE, ERR_CONTENT_BLANK_FILE_NAME, ERR_CONTENT_CREATE, 
	    ERR_CONTENT_UPDATE, ERR_CHANNEL_NOT_FOUND, ERR_CATEGORY_NOT_FOUND, ERR_CATEGORY_INSTANCE_NOT_FOUND, 
	    ERR_FRAMEWORK_NOT_FOUND, ERR_CONTENT_INVALID_PUBLISH_CHECKLIST, ERR_CONTENT_COPY_ARTIFACT, 
	    CONTENTTYPE_ASSET_CAN_NOT_COPY, ERR_CONTENT_RETIRE, ERR_CONTENT_MIMETYPE, ERR_CONTENT_INVALID_CHANNEL,
	    ERR_CHANNEL_BLANK_OBJECT, ERR_REQUEST_BLANK, ERR_INVALID_COUNT, ERR_INVALID_PUBLISHER, ERR_NOT_A_TEXTBOOK,
		ERR_NO_RESERVED_DIALCODES, ERR_NOT_A_CONTENT, ERR_ALL_DIALCODES_UTILIZED, ERR_INVALID_PRESIGNED_URL_TYPE, ERR_INVALID_INPUT, ERR_CONTENT_INVALID_FILE_NAME,
		ERR_CONTENT_NOT_DRAFT, ERR_METADATA_ISSUE, ERR_INVALID_CONTENT_ID, ERR_INVALID_REQUEST_FORMAT, ERR_CONTENT_NOT_IN_REVIEW;
}
