package com.ilimi.graph.dac.exception;

public enum GraphDACErrorCodes {

    ERR_DAC_UNKNOWN_EXCEPTION_000,

    ERR_DAC_SYS_EXCEPTION_001,

    ERR_DAC_INVALID_GRAPH_ID_002,

    ERR_DAC_GRAPH_ALREADY_EXISTS_003,

    ERR_DAC_GRAPH_NOT_FOUND_004,

    ERR_DAC_NODE_NOT_FOUND_005,

    ERR_DAC_INVALID_NODE_ID_006,
    
    ERR_DAC_NULL_DB_NODE_007,
    
    ERR_DAC_NULL_DB_REL_008,

    ERR_DAC_CREATE_GRAPH_EXCEPTION,
    
    ERR_DAC_DELETE_GRAPH_EXCEPTION,

    ERR_DAC_CREATE_RELATION_EXCEPTION,

    ERR_DAC_DELETE_RELATION_EXCEPTION,

    ERR_DAC_UPDATE_RELATION_EXCEPTION,

    ERR_DAC_CREATE_NODE_EXCEPTION,
    
    ERR_DAC_IMPORT_NODE_EXCEPTION,

    ERR_DAC_UPDATE_NODE_EXCEPTION,

    ERR_DAC_DELETE_NODE_EXCEPTION,
    
    ERR_DAC_GET_NODE_EXCEPTION,
    
    ERR_DAC_GET_NODE_PROPERTY,
    
    ERR_DAC_GET_NODE_LIST_EXCEPTION,
    
    ERR_DAC_GET_RELATIONS_EXCEPTION,
    
    ERR_DAC_CHECK_LOOP,
    
    ERR_DAC_CREATE_COLLECTION_EXCEPTION,
    
    ERR_DAC_DELETE_COLLECTION,
    
    ERR_DAC_SEARCH_NODES,
    
    ERR_DAC_TRAVERSAL;
}
