package com.ilimi.assessment.enums;

public enum AssessmentErrorCodes {
    ERR_ASSESSMENT_BLANK_TAXONOMY_ID,
    ERR_ASSESSMENT_BLANK_ITEM_ID,
    ERR_ASSESSMENT_BLANK_ITEM, 
    ERR_ASSESSMENT_BLANK_QUESTIONNAIRE,
    ERR_ASSESSMENT_BLANK_QUESTIONNAIRE_ID, 
    ERR_ASSESSMENT_BLANK_SET_CRITERIA
}
