package com.ilimi.graph.common.enums;

public enum CommonsDacParams {
    COMMENT, COMMENTS, COMMENT_ID, COMMENT_THREAD_ID, AUDIT_RECORD, AUDIT_RECORDS, AUDIT_RECORD_ID, OBJECT_ID, 
    OBJECT_VERSION, OBJECT_VERSION_ID, OBJECT_VERSIONS, OBJECT_VERSION_NUM
}
