- hosts: learningall
  pre_tasks:
    - name: Create learner group
      become: yes
      group:
        state: present
        name: "{{ learner_group }}"
        system: yes
    - name: Create learner user
      become: yes
      user:
        state: present
        name: "{{ learner_user }}"
        comment: learner user
        system: yes
        createhome: yes
        group: "{{ learner_group }}"
    - name: create folder data for learning
      become: yes
      file: path={{ item }} state=directory mode=0775 owner={{learner_user}} group={{learner_user}}
      with_items: "{{ learnings.paths }}"
  roles:
    - java
    - tomcat
    - ffmpeg
    - imagemagick
    - logstash
