- hosts: searchall
  pre_tasks:
    - name: Create learner group
      become: yes
      group:
        state: present
        name: "{{ learner_group }}"
        system: yes
    - name: Create learner user
      become: yes
      user:
        state: present
        name: "{{ learner_user }}"
        comment: learner user
        system: yes
        createhome: yes
        group: "{{ learner_group }}"
    - name: create folder data for learning
      become: yes
      file: path={{ item }} state=directory mode=0755 owner={{learner_user}} group={{learner_group}}
      with_items: "{{ searchs.paths }}"
  roles:
    - java
    - logstash
    - search-service
  serial: 1
