---
- name: "Copy validation schema files to Yarn Slaves"
  hosts: "yarn-slave"
  become: yes
  tasks:
   - name: cloning the telemetry schema repo
     git:
       repo: "{{schema_repo_url}}"
       dest: "{{telemetry_schema_directory}}"
       version: "{{version}}"
       force: yes
   - name: Create schema directory
     file: path={{telemetry_schema_directory}} owner=hduser group=hadoop recurse=yes state=directory

   - name: get schema dir names
     raw: find {{telemetry_schema_path}} -type f -name "*.*"
     register: schemas

   - name: change internal schema file reference
     replace: 
       dest: "{{item}}" 
       regexp: "http://localhost:7070/schemas/" 
       replace: "file://{{telemetry_schema_path}}/" 
       owner: hduser 
       group: hadoop
     with_items: "{{ schemas.stdout_lines }}"
