version: "3.0"
services:
  sunbird-neo4j:
    image: neo4j:3.3.0
    container_name: "sunbird_neo4j"
    ports:
      - 7473:7473
      - 7474:7474
      - 7687:7687
    volumes:
      - $sunbird_dbs_path/neo4j/data:/var/lib/neo4j/data
      - $sunbird_dbs_path/neo4j/logs:/var/lib/neo4j/logs
      - $sunbird_dbs_path/neo4j/plugins:/var/lib/neo4j/plugins
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_connector_https_advertised__address: "localhost:7473"
      NEO4J_dbms_connector_http_advertised__address: "localhost:7474"
      NEO4J_dbms_connector_bolt_advertised__address: "localhost:7687"

  sunbird-cassandra:
    image: cassandra:3.11.11
    container_name: "sunbird_cassandra"
    ports:
      - 9042:9042
    depends_on:
      - sunbird-neo4j
    volumes:
      - $sunbird_dbs_path/cassandra/data:/var/lib/cassandra
      - $sunbird_dbs_path/cassandra/logs:/opt/cassandra/logs
      - $sunbird_dbs_path/cassandra/backups:/mnt/backups

  sunbird-redis:
    image: redis:6.0.8
    container_name: "sunbird_redis"
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - $sunbird_dbs_path/redis/redis.conf:/usr/local/etc/redis/redis.conf

  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:2181

  kafka:
    image: 'wurstmeister/kafka:2.11-1.0.1'
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper