package com.ilimi.graph.dac.enums;

public enum GraphDACParams {

    GRAPH_ID, START_NODE_ID, END_NODE_ID, RELATION_TYPE, METADATA, PROPERTY_KEY, NODE, NODE_ID, NODE_IDS, PROPERTY_KEYS, COUNT, 
    NODE_LIST, RELATIONS, RELATION, PROPERTY, LOOP, MESSAGE, MESSAGES, OBJECT_TYPE, REQUIRED_METADATA_KEY, INDEXABLE_METADATA_KEY, 
    NON_INDEXABLE_METADATA_KEY, IN_RELATIONS_KEY, OUT_RELATIONS_KEY, SYSTEM_TAGS_KEY, SEQUENCE_ID, MEMBERS, COLLECTION_ID, COLLECTION_TYPE, MEMBER_ID, 
    INDEX, CARDINALITY, IMPORT_INPUT_OBJECT, SEARCH_CRITERIA, TRAVERSAL_DESCRIPTION, SUB_GRAPH, PATH, DEPTH, IS_MEMBER, SET_ID, CRITERIA, 
    IN_RELATIONS, OUT_RELATIONS, TAG_ID, TAG_NAME, ATTRIBUTE_NAME, DEFINITION_NODE, DEFINITION_NODES, GET_TAGS, METADATA_DEFINITIONS;
}
