---
- name: Create schema directory
  file: path={{telemetry_schema_directory}} owner=hduser group=hadoop recurse=yes state=directory
  become: yes

- name: Copy schemas folder
  copy: src=schemas dest={{telemetry_schema_directory}} owner=hduser group=hadoop
  become: yes

- name: get schema dir names
  raw: find {{telemetry_schema_path}} -type f -name "*.*"
  register: schemas

- name: change internal schema file reference
  replace: dest={{item}} regexp="http://localhost:7070/schemas/" replace="file://{{telemetry_schema_path}}/" owner=hduser group=hadoop
  with_items: "{{ schemas.stdout_lines }}"
  become: yes