package org.ekstep.orchestrator.interpreter.exception;

public enum ExecutionErrorCodes {

	ERR_SYSTEM_ERROR, ERR_INIT_ERROR, ERR_INVALID_REQUEST, ERR_SCRIPT_ERROR, ERR_INIT_BLANK_COMMAND, ERR_INIT_INVALID_COMMAND,
	ERR_INIT_BLANK_SCRIPT, ERR_INIT_INVALID_SCRIPT, ERR_EXEC_INVALID_REQUEST, ERR_EXEC_ERROR, ERR_SCRIPT_NOT_FOUND;
}
