package org.ekstep.assessment.enums;

public enum AssessmentErrorCodes {
    ERR_ASSESSMENT_BLANK_TAXONOMY_ID,
    ERR_ASSESSMENT_BLANK_ITEM_ID,
    ERR_ASSESSMENT_BLANK_ITEM,
    ERR_ASSESSMENT_BLANK_ITEM_SET_ID,
    ERR_ASSESSMENT_BLANK_QUESTIONNAIRE,
    ERR_ASSESSMENT_BLANK_QUESTIONNAIRE_ID, 
    ERR_ASSESSMENT_INVALID_SEARCH_CRITERIA, 
    ERR_ASSESSMENT_BLANK_CRITERIA, ERR_ASSESSMENT_INSUFFICIENT_ITEMS,
	ERR_ASSESSMENT_INVALID_REQUEST_FORMAT, ERR_ASSESSMENT_SAVE_BODY
}
