package org.ekstep.assessment.enums;

public enum AssessmentErrorCodes {
    ERR_ASSESSMENT_BLANK_TAXONOMY_ID,
    ERR_ASSESSMENT_BLANK_ITEM_ID,
    ERR_ASSESSMENT_BLANK_ITEM,
    ERR_ASSESSMENT_BLANK_ITEM_SET_ID,
    ERR_ASSESSMENT_BLANK_QUESTIONNAIRE,
    ERR_ASSESSMENT_BLANK_QUESTIONNAIRE_ID, 
    ERR_ASSESSMENT_INVALID_SEARCH_CRITERIA, 
    ERR_ASSESSMENT_BLANK_CRITERIA, ERR_ASSESSMENT_INSUFFICIENT_ITEMS,
	ERR_ASSESSMENT_INVALID_REQUEST_FORMAT, ERR_ASSESSMENT_SAVE_BODY,
    ERR_ASSESSMENT_UPDATE,
    ERR_ASSESSMENT_UPLOAD_FILE,
    ERR_ASSESSMENT_BULK_READ,
    ERR_ASSESSMENT_BULK_UPDATE,
    ERR_QUESTIONPAPER_FILE_GENERATE,
    ERR_QUESTIONPAPER_UPLOAD_FAILED
}
