package org.sunbird.common.enums;

public enum TaxonomyErrorCodes {

    ERR_TAXONOMY_ACTOR_SYSTEM_NOT_CREATED, 
    ERR_TAXONOMY_REQUEST_ROUTER_NOT_FOUND,
    ERR_TAXONOMY_BLANK_TAXONOMY_ID,
    ERR_TAXONOMY_EMPTY_INPUT_STREAM,
    ERR_TAXONOMY_EMPTY_SEARCH_CRITERIA,
    ERR_TAXONOMY_NULL_DEFINITION,
    ERR_TAXONOMY_EMPTY_INDEX_KEYS,
    ERR_TAXONOMY_BLANK_CONCEPT_ID,
    ERR_TAXONOMY_BLANK_CONCEPT,
    ERR_TAXONOMY_UPDATE_CONCEPT,
    ERR_TAXONOMY_GET_CONCEPTS,
    SYSTEM_ERROR,
    ERR_INVALID_UPLOAD_FILE,
    ERR_INVALID_UPLOAD_FILE_URL,
    ERR_MEDIA_UPLOAD_FILE, 
    ERR_TAXONOMY_INVALID_CONTENT, 
    ERR_NODE_CREATION,
    ERR_NODE_ACCESS_DENIED,
    ERR_CONTENT_OPERATION_DENIED,
    INVALID_CONTENT_ID, 
    ERR_CONTENT_MISSING_CONTENT_RESOURCE_TYPE,
	INVALID_REQUEST, ERR_YOUTUBE_LICENSE_VALIDATION,
	ERR_NODE_NOT_FOUND,
	ERR_CONTENT_NOT_FLAGGED,
	ERR_GOOGLE_DRIVE_SIZE_VALIDATION,
	ERR_INVALID_URL
}
