cassandra_backup_azure_container_name: lp-cassandra-backup

user: "{{ ansible_ssh_user }}"
restore_path: /home/{{user}}
backup_folder_name: cassandra_backup
backup_dir: "{{restore_path}}/cassandra_backup"

# This variable is added for the below reason -
# 1. Introduce a common variable for various clouds. In case of azure, it refers to container name, in case of aws / gcp, it refers to folder name
# 2. We want to avoid too many new variable introduction / replacement in first phase. Hence we will reuse the existing variable defined in private repo
#    or other default files and just assign the value to the newly introduced common variable
# 3. After few releases, we will remove the older variables and use only the new variables across the repos
cassandra_backup_storage: "{{ cassandra_backup_azure_container_name }}"
