- name: Ensure oci oss bucket exists
  command: oci os bucket get --name {{ oss_bucket_name }}

- name: Upload to oci oss bucket
  command: oci os object delete -bn {{ oss_bucket_name }} --name {{ oss_path }} --force
  async: 3600
  poll: 10