---
- name: delete files from oci oss bucket 
  include: delete.yml
  
- name: delete folders from oci oss bucket recursively
  include: delete-folder.yml
  

- name: download file from oss
  include: download.yml

- name: upload files from a local to oci oss
  include: upload.yml

- name: upload files and  folder from local directory to oci oss
  include: upload-folder.yml
 

