
- name: Stop logstash process
  become: yes
  systemd: name=logstash state=stopped
  ignore_errors: yes

- name: Copy logstash configuration files for platform
  become: yes
  become_user: "{{learner_user}}"
  template: src=logstash-lp.j2  dest={{learner_user_home}}/logstash-{{logstash_version}}/logstash-lp.conf

- name: Copy the kernel extension jar file
  become: yes
  become_user: "{{learner_user}}"
  copy: src={{ zip_file }} dest={{ neo4j_home }}/plugins/ owner={{ learner_user }} group={{ learner_user }}

- name: Copy the custom procedures jar file
  become: yes
  become_user: "{{learner_user}}"
  copy: src={{ custom_procs_file }} dest={{ neo4j_home }}/plugins/ owner={{ learner_user }} group={{ learner_user }}

- name: Start logstash process
  become: yes
  systemd: name=logstash state=started
