package org.sunbird.graph.exception;

public enum GraphRelationErrorCodes {

    ERR_RELATION_UNKNOWN_EXCEPTION_000,

    ERR_RELATION_SYS_EXCEPTION_001,

    ERR_INVALID_RELATION,
    
    ERR_RELATION_CREATE,
    
    ERR_RELATION_VALIDATE,

    ERR_RELATION_DELETE,

    ERR_RELATION_UPDATE,

    ERR_RELATION_GET_PROPERTY,

    ERR_RELATION_SET_PROPERTY,

    ERR_RELATION_REMOVE_PROPERTY,
    
    ERR_RELATION_UNSUPPORTED_OPERATION;
}
