learner_user: learning
learner_group: learning
description: LP Search service
service_path: /home/{{learner_user}}/platform/service
script_name: "search-service"
script_dir: "{{ service_path }}"
grep_key: play.core.server.ProdServerStart
process: "/usr/bin/java"
search_root: /home/{{learner_user}}/platform/search
service_args: "-Dconfig.file={{ search_root }}/search-service.conf"
search_home: /home/{{learner_user}}/platform/search/search-manager
process_home: ""
app_home: "{{ search_home }}"
process_args: -- -cp '{{ app_home }}/lib/*' {{ service_args }} play.core.server.ProdServerStart {{ app_home }}