package com.ilimi.orchestrator.mgr.exception;

public enum OrchestratorErrorCodes {

	ERR_BLANK_SCRIPT, ERR_BLANK_COMMAND, ERR_INVALID_SCRIPT, ERR_INVALID_COMMAND, ERR_CREATE_SCRIPT, ERR_CREATE_COMMAND, 
	ERR_LIST_SCRIPTS, ERR_LIST_COMMANDS, ERR_SYSTEM_ERROR, ERR_SCRIPT_NOT_FOUND, ERR_COMMAND_NOT_FOUND,
	ERR_INVALID_REGISTER_REQUEST, ERR_UPDATE_SCRIPT, ERR_UPDATE_COMMAND,;
}
