package com.ilimi.common.enums;

public enum TaxonomyErrorCodes {

    ERR_TAXONOMY_ACTOR_SYSTEM_NOT_CREATED, 
    ERR_TAXONOMY_REQUEST_ROUTER_NOT_FOUND,
    ERR_TAXONOMY_BLANK_TAXONOMY_ID,
    ERR_TAXONOMY_EMPTY_INPUT_STREAM,
    ERR_TAXONOMY_EMPTY_SEARCH_CRITERIA,
    ERR_TAXONOMY_NULL_DEFINITION,
    ERR_TAXONOMY_EMPTY_INDEX_KEYS,
    ERR_TAXONOMY_BLANK_CONCEPT_ID,
    ERR_TAXONOMY_BLANK_CONCEPT,
    ERR_TAXONOMY_UPDATE_CONCEPT,
    ERR_TAXONOMY_GET_CONCEPTS,
    SYSTEM_ERROR,
    ERR_INVALID_UPLOAD_FILE,
    ERR_MEDIA_UPLOAD_FILE, 
    ERR_TAXONOMY_INVALID_CONTENT, 
    ERR_NODE_CREATION, 
    ERR_INVALID_UPLOAD_File;
}
