package com.ilimi.graph.exception;

public enum GraphEngineErrorCodes {

    ERR_GRAPH_UNKNOWN_EXCEPTION_000,

    ERR_GRAPH_SYS_EXCEPTION_001,

    ERR_GRAPH_INVALID_GRAPH_ID_002,

    ERR_GRAPH_CREATE_GRAPH_ERROR,

    ERR_GRAPH_LOAD_GRAPH_ERROR,

    ERR_GRAPH_VALIDATE_GRAPH_ERROR,

    ERR_GRAPH_DELETE_GRAPH_ERROR,

    ERR_GRAPH_SAVE_DEF_NODE_ERROR,

    ERR_GRAPH_GET_DEF_NODE_ERROR,

    ERR_GRAPH_INVALID_PROPERTY,

    ERR_GRAPH_ADD_NODE_ERROR,

    ERR_GRAPH_REMOVE_NODE_ERROR,

    ERR_GRAPH_UPDATE_NODE_ERROR,

    ERR_GRAPH_GET_NODE_ERROR,

    ERR_GRAPH_SEARCH_ERROR,

    ERR_GRAPH_GET_DESCENDANTS,

    ERR_GRAPH_CREATE_SEQUENCE,

    ERR_GRAPH_ADD_SEQUENCE_MEMBER,

    ERR_GRAPH_REMOVE_SEQUENCE_MEMBER,

    ERR_GRAPH_DROP_SEQUENCE,

    ERR_GRAPH_GET_SEQUENCE_MEMBERS,

    ERR_GRAPH_IS_SEQUENCE_MEMBER,

    ERR_GRAPH_COLLECTION_GET_CARDINALITY,

    ERR_GRAPH_IMPORT_GRAPH_ERROR,

    ERR_GRAPH_EXPORT_GRAPH_ERROR,

    ERR_INVALID_NODE,

    ERR_GRAPH_UNSUPPORTED_OPERATION,

    ERR_GRAPH_INVALID_COLLECTION_TYPE,

    ERR_GRAPH_SEARCH_NODES,

    ERR_GRAPH_TRAVERSAL,

    ERR_GRAPH_GET_CHILDREN,

    ERR_GRAPH_CREATE_SET,

    ERR_GRAPH_SET_CRITERIA,

    ERR_GRAPH_ADD_SET_MEMBER,

    ERR_GRAPH_REMOVE_SET_MEMBER,

    ERR_GRAPH_GET_SET_MEMBERS,

    ERR_GRAPH_IS_SET_MEMBER,

    ERR_GRAPH_DROP_SET,

    ERR_EMPTY_TAG_NAME,

    ERR_GRAPH_CREATE_TAG,

    ERR_GRAPH_ADD_TAG_MEMBER,

    ERR_GRAPH_REMOVE_TAG_MEMBER,

    ERR_GRAPH_GET_TAG_MEMBERS,

    ERR_GRAPH_IS_TAG_MEMBER,

    ERR_GRAPH_DROP_TAG,

    ERR_GRAPH_COLLECTION_ADD_MEMBER,

    ERR_GRAPH_COLLECTION_REMOVE_MEMBER,

    ERR_GRAPH_DROP_COLLECTION,

    ERR_GRAPH_COLLECTION_GET_MEMBERS,

    ERR_GRAPH_ADD_TAGS;
}
