---
- name: Add Microsfot signing key
  become: yes
  become_user: root
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Microsoft repository into sources list
  become: yes
  become_user: root
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release | lower }} main"
    state: present

- name: Install azue cli and dependent packages
  become: yes
  become_user: root
  apt:
    pkg:
    - ca-certificates
    - curl
    - apt-transport-https
    - lsb-release
    - gnupg
    - "azure-cli=2.33.1-1~{{ ansible_distribution_release | lower }}"

- name: Install azcopy
  become: yes
  become_user: root
  shell: |
    which azcopy || ( \
    mkdir /tmp/azcopy && cd /tmp/azcopy && \
    wget -O azcopy_v10.tar.gz https://aka.ms/downloadazcopy-v10-linux && tar -xf azcopy_v10.tar.gz --strip-components=1 \
    && mv azcopy /usr/local/bin \
    && rm -rf /tmp/azcopy )
