---
- name: Create directory for additional config
  file: path={{object_denormalization_additional_config_dir}} owner=hduser group=hadoop recurse=yes state=directory

- name: Copy Object denormalization additional config
  template: src=object-denormalization-additional-config.json dest={{object_denormalization_additional_config}} owner=hduser group=hadoop

- name: Copy Primary es router additional config
  template: src=es-router-additional-config.json dest={{es_router_additional_config}} owner=hduser group=hadoop

- name: Copy Secondary es router additional config
  template: src=es-router-additional-secondary-config.json dest={{es_router_additional_secondary_config}} owner=hduser group=hadoop
