---
yarn_deploy_dir: /home/ecosystem/.deploy
repo_folder: /home/hduser/Ecosystem-Platform
hadoop_tarball: hadoop-{{hadoop_version}}.tar.gz
hadoop_download_url: https://archive.apache.org/dist/hadoop/common/hadoop-{{hadoop_version}}/{{hadoop_tarball}}
scala_tarball: scala-{{scala_version}}.tgz
scala_download_url: http://www.scala-lang.org/files/archive/{{scala_tarball}}
hadoop_yarn_home: /usr/local/hadoop-{{hadoop_version}}
hadoop_version: 2.7.2
scala_version: 2.10.4

yarn_config_override: true
yarn_vmem_check_enabled: false
yarn_vmem_pmem_ratio: 2.1
yarn_vcores: 16
yarn_resource_memory: 20000
