---
- name: Delete existing configuration files
  become: yes
  become_user: "{{learner_user}}"
  file: name=/home/learning/content_tool state=absent

- name: Create directory
  become: yes
  become_user: "{{learner_user}}"
  file: name=/home/learning/content_tool state=directory mode=755 owner="{{learner_user}}" group="{{learner_user}}"

- name: Copy application.conf file
  become: yes
  become_user: "{{learner_user}}"
  template: src=application.conf.j2 dest=/home/learning/content_tool/application.conf

- name: Copy jar file.
  become: yes
  become_user: "{{learner_user}}"
  copy: src=content-tool-1.0-SNAPSHOT.jar dest=/home/learning/content_tool/
