learner_user: learning
learner_group: learning
learner_user_home: /home/{{learner_user}}
tomcat_major_version: 8
tomcat_minor_version: 0.36
tomcat_home: "{{learner_user_home}}/apache-tomcat-{{tomcat_major_version}}.{{tomcat_minor_version}}"
tomcat_tar_ball: "tomcat-{{tomcat_major_version}}/v{{tomcat_major_version}}.{{tomcat_minor_version}}/bin/apache-tomcat-{{tomcat_major_version}}.{{tomcat_minor_version}}.tar.gz"
tomcat_init_mem: -Xms1024m
tomcat_max_mem: -Xmx4096m

