---
# This role is for installing jdk1.8.0_121 
# Because cassandra 3.7 is not compatible with other latest java versions

- name: Uncompressing and copying to system path
  unarchive:
    src: https://sunbirdpublic.blob.core.windows.net/installation/jdk-8u121-linux-x64.tar.gz
    dest: /opt/
    remote_src: yes
    keep_newer: yes
  register: tar

- name: Updating java jdk to system path
  shell: |
    update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_121/bin/java 9999
    update-alternatives --install /usr/bin/javac javac /opt/jdk1.8.0_121/bin/java 9999
  when: tar.changed

- name: Checking java version
  shell: java -version
  register: java

- name: Java version
  debug:
    var: java.stderr

- name: Remove post install script
  file:
    path: /var/lib/dpkg/info/oracle-java8-installer.postinst
    state: absent
