---
- name: Download Tomcat
  become: yes
  become_user: "{{learner_user}}"
  get_url: url=http://archive.apache.org/dist/tomcat/{{tomcat_tar_ball}} dest={{learner_user_home}}/ timeout=1000 force=no owner={{learner_user}} group={{learner_user}}

- name: Extract archive
  become: yes
  become_user: "{{learner_user}}"
  unarchive: src={{learner_user_home}}/apache-tomcat-{{tomcat_major_version}}.{{tomcat_minor_version}}.tar.gz dest={{learner_user_home}} copy=no group={{learner_user}} owner={{learner_user}} creates={{ tomcat_home }}

- name: set permission
  become: yes
  file: path={{ tomcat_home }}  mode=0755 owner={{learner_user}} group={{learner_user}} recurse=yes

- name: Symlink install directory
  become: yes
  file: src={{ tomcat_home }} path=/usr/share/tomcat state=link
  ignore_errors: yes

- name: Change ownership of Tomcat installation
  become: yes
  become_user: "{{learner_user}}"
  file: path=/usr/share/tomcat/ owner={{learner_user}} group={{learner_user}} mode=0775 state=directory recurse=yes

- name: add templates for learning
  become: yes
  become_user: "{{learner_user}}"
  template: src={{ item.name }} dest={{ item.destination }}
  with_items:
    - { name: 'server.xml', destination: '/usr/share/tomcat/conf/' }
    - { name: 'catalina.j2', destination: '{{ tomcat_home }}/bin/catalina.sh' }

- name: Install Tomcat init script
  become: yes
  template: src=tomcat-initscript.j2 dest=/etc/init.d/tomcat mode=755

- name: set permission
  become: yes
  file: path={{ tomcat_home }}  mode=0775 owner={{learner_user}} group={{learner_user}} recurse=yes
