learner_user: learning
learner_user_home: /home/{{learner_user}}
logstash_version: 6.3.1
neo4j_dir: neo4j-learning
neo4j_home: "{{learner_user_home}}/{{neo4j_dir}}/neo4j-enterprise-3.3.0"
graphevent_kafka_url: "{{groups['processing-cluster-zookeepers']|join(':9092,')}}:9092"
graphevent_kafka_topic_id: "{{env}}.learning.graph.events"
backend_event_topic_id: "{{env}}.telemetry.backend"

zip_file: #learning-graphextension jar file
custom_procs_file: # custom-procedures jar file