cassandra_repo: "deb http://debian.datastax.com/datastax-ddc 3.7 main"
data_file_directories: /data/cassandra/data
commitlog_directory: /data/cassandra/commitlog
saved_caches_directory: /data/cassandra/saved_caches
seeds: "{{ inventory_hostname }}"
listen_address: "{{ inventory_hostname }}"
broadcast_rpc_address: "{{ inventory_hostname }}"
paths: ['/data/cassandra', '/data/cassandra/commitlog', '/data/cassandra/data', '/data/cassandra/saved_caches', '/data/cassandra/logs']
cassandra_user: cassandra
cassandra_lib: "/usr/share/cassandra/lib/"
cassandra_lib_src: "templates/cassandra-lib.tgz"
cassandra_conf: "/etc/cassandra/"
cassandra_env_file: "/etc/cassandra/cassandra-env.sh"
keyspace_prefix: '{{ env }}_'
replication_factor: 1
