- hosts: localhost
  gather_facts: no
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  tasks:
    - name: Ensure azure blob storage container exists
      include_role:
        name: azure-cloud-storage
        tasks_from: container-create.yml
      vars:
        blob_container_name: "elasticsearch-snapshots"
        container_public_access: "off"
        storage_account_name: "{{ azure_management_storage_account_name }}"
        storage_account_sas_token: "{{ azure_management_storage_account_sas }}"
      when: cloud_service_provider == "azure"

- hosts: composite-search-cluster
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  roles:
    - role: es-azure-snapshot
      when: cloud_service_provider == "azure"
    - role: es-s3-snapshot
      when: cloud_service_provider == "aws"
    - role: es-gcs-snapshot
      when: cloud_service_provider == "gcloud"
    - role: es5-snapshot-purge
  tags:
    - es_backup
  run_once: true
