---
- hosts: composite-search-cluster
  name: Setup composite search ES cluster
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  become: yes
  pre_tasks:
    - name: Uncompressing and copying to system path
      unarchive:
        src: https://sunbirdpublic.blob.core.windows.net/installation/jre-8u144-linux-x64.tar.gz
        dest: /opt/
        remote_src: yes
        keep_newer: yes
      become: yes
      register: tar
    - name: Updating java jre to system path
      become: yes
      shell: update-alternatives --install /usr/bin/java java /opt/jre1.8.0_144/bin/java 9999
    - name: Registering node name
      set_fact:
        es_instance_name: "{% for servername in play_hosts %}{% if inventory_hostname==servername %}cs-node-{{ loop.index }}{% endif %}{% endfor %}"

  roles:
    - { role: es6, 
        es_config: {
          cluster.name: "elasticsearch-composite-search",
          discovery.zen.ping.unicast.hosts: "{{ groups['composite-search-cluster'] }}",
          http.port: 9200,
          transport.tcp.port: 9300,
          node.data: "true",
          node.master: "true",
          bootstrap.memory_lock: true,
        },
        es_etc_discovery_zen_ping_unicast_hosts: "{{ groups['composite-search-cluster'] }}",
        es_etc_cluster_name: "elasticsearch-composite-search"
      }
