---
- hosts: "{{ es_restore_host }}"
  become: yes
  vars:
    - es_restore_host: "{{ es_restore_host }}"
    - snapshot_base_path: "{{ snapshot_base_path }}"
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  roles:
    - es-azure-restore
  tags:
    - es_restore
