- hosts: learning-neo4j-node1  #if it is a cluster learning-neo4j-node1 should be always master node
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  become: yes
  become_user: "{{ learner_user }}"
  roles:
    - neo4j-backup
