- hosts: learning-neo4j-node1  #if it is a cluster learning-neo4j-node1 should be always master node
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  environment:
    AZURE_STORAGE_ACCOUNT: "{{ backup_azure_storage_account_name }}"
    AZURE_STORAGE_KEY: "{{ backup_azure_storage_access_key }}"
  become: yes
  become_user: "{{ learner_user }}"
  roles:
    - neo4j-backup 
