---
- hosts: lp-yarn
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  tasks:
    - name: Create group
      group: 
        name: hadoop 
        state: present
    - name: Create user
      user: 
        name: hduser 
        comment: "hduser" 
        group: hadoop 
        groups: sudo 
        shell: /bin/bash

- name: Install samza job server
  hosts: "lp-yarn-master"
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets/lp_secrets.yml"
  roles:
    - java
    - yarn
    - samza-job-server

# # As of ansible2.5 delegation and inlcude tasks file won't work
# # with looping. So this is a possible workaround
# - name: Running common tasks in yarn slaves
#   vars_files:
#     - ./roles/yarn/defaults/main.yml
#   hosts: "lp-yarn-slave"
#   become: yes
#   tasks:
#     - include: ./roles/yarn/tasks/common.yml
#     - include: ./roles/yarn/templates

- name: Install java on all yarn slaves
  hosts: "lp-yarn-slave"
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets/lp_secrets.yml"
  remote_user: hduser
  roles:
    - java
