package com.ilimi.taxonomy.enums;

public enum ContentErrorCodes {
    ERR_CONTENT_BLANK_TAXONOMY_ID, ERR_CONTENT_BLANK_OBJECT, ERR_CONTENT_INVALID_UPLOAD_OBJECT, ERR_CONTENT_BLANK_OBJECT_ID, ERR_CONTENT_INVALID_OBJECT_TYPE, ERR_CONTENT_INVALID_PARAM, 
    ERR_CONTENT_BLANK_UPLOAD_OBJECT, ERR_CONTENT_UPLOAD_FILE, ERR_CONTENT_INVALID_SEARCH_CRITERIA;
}
