package com.ilimi.taxonomy.enums;

public enum LearningObjectErrorCodes {

    ERR_LOB_BLANK_OBJECT_TYPE, ERR_LOB_BLANK_LEARNING_OBJECT_ID, ERR_LOB_BLANK_LEARNING_OBJECT, ERR_LOB_UPDATE_OBJECT, 
    ERR_GAME_INVALID_PARAM;
}
