learner_user: learning
learner_user_home: /home/{{learner_user}}

learning_neo4j_bolt_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:7687
language_neo4j_bolt_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:8687
learning_read_elb_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:7687
learning_write_elb_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:7687
language_read_elb_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:8687
language_write_elb_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:8687
object_bookmark_expiry_in_seconds: 15
environment_id: 10000000
search_index_host: "{{ groups['composite-search-cluster'][0] }}:9200"
hierarchy_keyspace_name: "{{env}}_hierarchy_store"
content_keyspace_name: "{{env}}_content_store"
youtube_app_name: fetch-youtube-license
instance: "{{env}}"
instance_name: 

lp_cassandra_connection: "{{groups['cassandra']|join(':9042,')}}:9042"
