package org.ekstep.learning.common.enums;

public enum ContentErrorCodes {
	 ERR_CONTENT_BLANK_TAXONOMY_ID, ERR_CONTENT_BLANK_OBJECT, ERR_CONTENT_INVALID_UPLOAD_OBJECT,
	    ERR_CONTENT_BLANK_OBJECT_ID, ERR_CONTENT_INVALID_OBJECT_TYPE, ERR_CONTENT_INVALID_PARAM, 
	    ERR_CONTENT_BLANK_UPLOAD_OBJECT, ERR_CONTENT_UPLOAD_FILE, ERR_CONTENT_INVALID_SEARCH_CRITERIA,
	    ERR_CONTENT_INVALID_BUNDLE_CRITERIA, ERR_CONTENT_NOT_FOUND, ERR_CONTENT_BLANK_ID, ERR_CONTENT_BLANK_PUBLISHER, ERR_CONTENT_PUBLISH, 
	    ERR_CONTENT_EXTRACT, ERR_INVALID_RELATION_NAME, ERR_ECAR_BUNDLE_FAILED, ERR_CONTENT_SEARCH_ERROR ,ERR_CONTENT_JSON_INVALID,ERR_CONTENT_BODY_INVALID, ERR_CONTENT_WP_JSON_PARSE_ERROR, ERR_CONTENT_WP_XML_PARSE_CONFIG_ERROR, ERR_CONTENT_WP_NOT_WELL_FORMED_XML, ERR_CONTENT_WP_XML_IO_ERROR, ERR_CONTENT_WP_OBJECT_CONVERSION, ERR_CONTENT_OPTIMIZE, INVALID_NODE, INVALID_EXTRACTION, INVALID_ECAR, INVALID_ARTIFACT, INVALID_FILE, EXTRACTION_ERROR;
}
