package org.sunbird.compositesearch.enums;

public enum SearchOperations {
	INDEX_SEARCH, LANGUAGE_SEARCH, METRICS, COUNT, GROUP_SEARCH_RESULT_BY_OBJECTTYPE, MULTI_LANGUAGE_WORD_SEARCH, MULTI_LANGUAGE_SYNSET_SEARCH, HEALTH;
}
